config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :registered_applications

  namespace :api, defaults: { format: :json } do  # defaults tells routes to get in JSON form. seperates API routes from rest of app routes
    match '/events', to: 'events#preflight', via: [:options]  # CORS implementation
  	resources :events, only: [:create]            # API need only support 1 route to record new events
  end

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications
  has_many :events, :through =>:registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_filter :set_access_control_headers

	def set_access_control_headers
		headers['Access-Control-Allow_Origin'] = '*'  # allow request from origin
		headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS' # permit POST, GET, OPTIONS request methods
		headers['Access-Control-Allow-Headers'] = 'Content-Type, application/json' # allow header Content-Type (used in HTTP requests to declare type of data being sent)
	end
  
  def create
  	registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
		
		if registered_application.nil?
			render json: "Unregistered Application", status: :unprocessable_entry
		else
			@event = registered_application.events.build(event_params)

			if @event.save
				render json: @event, status: :created
			else
				render json: { errors: @event.errors }, status: :unprocessable_entry
			end
		end
  end

  def preflight
  	head 200
  end

  private

  def event_params
  	params.require(:event).permit(:name)
  end
end

app/controllers/api_controller.rb
class APIController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user! 

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :require_sign_in
  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new
    @registered_application.name = params[:registered_application][:name]
    @registered_application.name = params[:registered_application][:url]

    if @registered_application.save
      flash[:notice] = "Application registered successfully"
      redirect_to [@registered_application]
    else
      flash[:alert] = "Failed to regiater Application"
      redirect_to :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.update_attributes(registered_application_params)
      flash[:notice] = "Successfully updated \"#{@registered_application.name}\"."
      redirect_to registered_applications_path
    else
      flash[:error] = "Failed to update Application"
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" deleted successfully"
      redirect_to registered_applications_path
    else
      flash[:alert] = "Failed to delete Application" 
      render :show
    end
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end

  def require_sign_in 
    unless current_user
      flash[:alert] = "You must sign in to do that!"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/api_helper.rb
module APIHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <meta name="viewport", content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://www.gstatic.com/charts/loader.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<div class="container">
  		<ul class="nav nav-tabs">
  			<li><%= link_to "Home", welcome_index_path %></li>
  			<li><%= link_to "My Apps", registered_applications_path %></li>
  			<li><%= link_to "About", welcome_about_path %></li>
  		</ul>

  		<div class="container">
        <div class="col-md-8">
          <div class="pull-right user-info">
            <% if user_signed_in? %>
              Signed in as: <strong><%= current_user.email %></strong> | 
              <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> - 
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:notice] %>
          </div>
        <% elsif flash.now[:alert] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash.now[:alert] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/registered_applications/_registered_application.html.erb
<%= link_to registered_application.name, registered_application %> 
	<hr>

app/views/registered_applications/edit.html.erb
<div class="row">
	<div class="col-md-8">	
		<%= form_for @registered_application do |f| %>
			<div class="form-group">
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter Application Name" %>
			</div>

			<div class="form-group">
				<%= f.text_field :url, class: 'form-control', placeholder: "Enter Application URL" %>
			</div>

			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registered_applications/index.html.erb
<h1>My Apps</h1>
<div class="row">
	<div class="col-md-4">
		<%= link_to "Register a new Application", new_registered_application_path, class: 'btn btn-primary' %>
	</div>

	<div class="col-md-8">
		<% if @registered_applications.any? %>
			<%= render @registered_applications %>
		<% end %>
	</div>
</div>

app/views/registered_applications/new.html.erb
<div class="row">
	<div class="col-md-8">
		<%= form_for @registered_application do |f| %>
			<div class="form-group">
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter Application Name" %>
			</div>
			
			<div class="form-group">
				<%= f.text_field :url, class: 'form-control', placeholder: "Enter Application URL" %>
			</div>

			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end%>
	</div>
</div>

app/views/registered_applications/show.html.erb
<div class="container">
	<h1 style="text-align: left;">Events</h1>
	<div class="col-md-14">
		<div class="media">
			<div class="media-heading">
				<h2><%= @registered_application.name %></h2>
				<h3><%= @registered_application.url %></h3>
				<hr>
			</div>
		</div>
	</div>
</div>
<hr>
<div class="container">
	<div class="col-md-8">
		<% if @registered_application.events.any? %>
			<div id="chart-1" style="height: 300px">
				<%= pie_chart @registered_application.events.group(:name).count %>
			</div>
			<div id="chart-2" style="height: 150px">
				<%= line_chart @registered_application.events.group_by_day(:created_at).count %>
			</div>
		<% end %>
	</div>
</div>
<div class="col-md-col-2">
	<%= link_to "Update Application", edit_registered_application_path, class: 'btn btn-success' %>
	<%= link_to "Unregister Application", @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: "Do you want to delete Application" } %>
	<%= link_to "Back", registered_applications_path, class: 'btn btn-info' %>
</div>

app/views/welcome/about.html.erb
<div class="container-fluid">
	<div class="row">
		<h1 class="about-title">About</h1>
		<p style="text-align: center;">An application build in cooperation with Bloc.io</p>
	</div>
</div>
<%= link_to "Back", root_path, class: 'btn btn-info' %>

app/views/welcome/index.html.erb
<h1>BlocMetrics</h1>
<div class="jumbotron">
  <p id='index-title'><%= link_to "Sign In", new_user_session_path %> or
 		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> today!</p>
 </div>